export const OBTENER_PUNTAJES_ESTUDIANTES = 'app/dashboard/OBTENER_PUNTAJES_ESTUDIANTES'
export const OBTENER_PUNTAJES_ESTUDIANTES_SUCCESS = 'app/dashboard/OBTENER_PUNTAJES_ESTUDIANTES_SUCCESS'
export const CHANGE = 'app/dashboard/CHANGE'
export const OBTENER_MUNICIPIOS = 'app/dashboard/OBTENER_MUNICIPIOS'
export const OBTENER_MUNICIPIOS_SUCCESS = 'app/dashboard/OBTENER_MUNICIPIOS_SUCCESS'

